#!/usr/bin/env python3
"""Audit data/*.json for quality defects and write docs/roadmap/DATA_AUDIT.md.

Read-only with respect to data/: it never writes, or otherwise modifies, any
file under data/. Run with --check to just print a summary and exit non-zero
if any defect count is above zero (no report is written in that mode).
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"
TOPICS_JSON = DATA_DIR / "topics.json"
REPORT_PATH = ROOT / "docs" / "roadmap" / "DATA_AUDIT.md"

FALLBACK_TOPIC_IDS = ["phil", "hist-events", "hist-chars"]

REQUIRED_KEYS = ["name", "dates", "y", "desc", "url"]

DESC_BATCH_SIZE = 40
TLDR_BATCH_SIZE = 50


def load_topic_ids():
    if TOPICS_JSON.exists():
        topics = json.loads(TOPICS_JSON.read_text(encoding="utf-8")).get("topics", [])
        ids = [t["id"] for t in topics if "id" in t]
        if ids:
            return ids
    return list(FALLBACK_TOPIC_IDS)


def load_topic(topic_id):
    path = DATA_DIR / f"{topic_id}.json"
    doc = json.loads(path.read_text(encoding="utf-8"))
    return doc["meta"], doc["entries"]


def is_missing(value):
    return value is None or value == "" or value == []


def is_truncated_desc(entry):
    desc = (entry.get("desc") or "").strip()
    return desc.endswith("…") or desc.endswith("...")


def audit_topic(topic_id, meta, entries):
    """Return a dict describing every defect found for one topic."""
    n = len(entries)

    truncated = sorted(
        (e.get("name", "") for e in entries if is_truncated_desc(e)),
        key=lambda s: s,
    )

    no_tldr = sorted(
        (e.get("name", "") for e in entries if is_missing(e.get("tldr"))),
        key=lambda s: s,
    )
    tldr_eq_desc = sorted(
        (
            e.get("name", "")
            for e in entries
            if not is_missing(e.get("tldr")) and e.get("tldr") == e.get("desc")
        ),
        key=lambda s: s,
    )
    # no_tldr and tldr_eq_desc are mutually exclusive per entry (an entry can't
    # simultaneously have a missing tldr and a tldr equal to desc), so this is a
    # plain concatenation, not a set union — a set would silently collapse two
    # distinct entries that happen to share the same `name`.
    tldr_needed = sorted(no_tldr + tldr_eq_desc, key=lambda s: s)

    name_counts = {}
    for e in entries:
        name = e.get("name", "")
        name_counts[name] = name_counts.get(name, 0) + 1
    duplicate_names = sorted(
        (name for name, count in name_counts.items() if count > 1),
        key=lambda s: s,
    )

    missing_required = sorted(
        (
            e.get("name") or "<unnamed entry>"
            for e in entries
            if any(is_missing(e.get(k)) for k in REQUIRED_KEYS)
        ),
        key=lambda s: s,
    )

    filters = meta.get("filters", [])
    filter_defects = {}
    filter_distribution = {}
    for flt in filters:
        key = flt["key"]
        multi = bool(flt.get("multiValue"))
        options = flt.get("options", [])
        options_set = set(options)

        bad_names = []
        dist = {opt: 0 for opt in options}
        for e in entries:
            value = e.get(key)
            if multi:
                values = value if isinstance(value, list) else []
                bad = is_missing(value) or not isinstance(value, list) or any(
                    v not in options_set for v in values
                )
                for v in values:
                    if v in dist:
                        dist[v] += 1
            else:
                bad = is_missing(value) or value not in options_set
                if value in dist:
                    dist[value] += 1
            if bad:
                bad_names.append(e.get("name", ""))

        filter_defects[flt["id"]] = sorted(bad_names, key=lambda s: s)
        filter_distribution[flt["id"]] = {"label": flt.get("label", flt["id"]), "counts": dist}

    def chunk(names, size):
        return [names[i : i + size] for i in range(0, len(names), size)]

    return {
        "id": topic_id,
        "title": meta.get("title", topic_id),
        "count": n,
        "truncated_desc": truncated,
        "truncated_desc_batches": chunk(truncated, DESC_BATCH_SIZE),
        "no_tldr": no_tldr,
        "tldr_eq_desc": tldr_eq_desc,
        "tldr_needed_batches": chunk(tldr_needed, TLDR_BATCH_SIZE),
        "duplicate_names": duplicate_names,
        "missing_required": missing_required,
        "filter_defects": filter_defects,
        "filter_distribution": filter_distribution,
    }


def build_report():
    return [audit_topic(tid, *load_topic(tid)) for tid in load_topic_ids()]


def render_markdown(report):
    lines = []
    lines.append("# Data audit")
    lines.append("")
    lines.append(
        "Generated by `tools/audit_data.py`. Do not hand-edit — rerun the script to refresh."
    )
    lines.append("")

    lines.append("## Summary")
    lines.append("")
    lines.append(
        "| Topic | Entries | Truncated desc | Missing tldr | tldr == desc | "
        "Duplicate names | Missing required fields | Filter defects |"
    )
    lines.append("|---|---|---|---|---|---|---|---|")
    for t in report:
        filter_defect_total = sum(len(v) for v in t["filter_defects"].values())
        lines.append(
            f"| {t['id']} | {t['count']} | {len(t['truncated_desc'])} | "
            f"{len(t['no_tldr'])} | {len(t['tldr_eq_desc'])} | "
            f"{len(t['duplicate_names'])} | {len(t['missing_required'])} | "
            f"{filter_defect_total} |"
        )
    lines.append("")

    for t in report:
        lines.append(f"## {t['id']} — {t['title']}")
        lines.append("")

        lines.append("### Duplicate names")
        lines.append("")
        if t["duplicate_names"]:
            for name in t["duplicate_names"]:
                lines.append(f"- {name}")
        else:
            lines.append("None.")
        lines.append("")

        lines.append("### Missing required fields")
        lines.append("")
        if t["missing_required"]:
            for name in t["missing_required"]:
                lines.append(f"- {name}")
        else:
            lines.append("None.")
        lines.append("")

        lines.append("### Filter distribution")
        lines.append("")
        if t["filter_distribution"]:
            for filter_id, info in t["filter_distribution"].items():
                lines.append(f"#### {info['label']} (`{filter_id}`)")
                lines.append("")
                lines.append("| Value | Count |")
                lines.append("|---|---|")
                for opt, count in info["counts"].items():
                    lines.append(f"| {opt} | {count} |")
                defects = t["filter_defects"].get(filter_id, [])
                lines.append(f"| _missing / invalid_ | {len(defects)} |")
                lines.append("")
                if defects:
                    lines.append(f"Entries with a missing/invalid `{filter_id}` value:")
                    lines.append("")
                    for name in defects:
                        lines.append(f"- {name}")
                    lines.append("")
        else:
            lines.append("No filters defined for this topic.")
            lines.append("")

        lines.append(f"### {t['id']} — truncated desc — batches")
        lines.append("")
        total = len(t["truncated_desc"])
        batches = t["truncated_desc_batches"]
        if total:
            lines.append(
                f"Total: {total} entries across {len(batches)} batches "
                f"({DESC_BATCH_SIZE} per batch)."
            )
            lines.append("")
            for i, batch in enumerate(batches, start=1):
                lines.append(f"#### Batch {i}")
                lines.append("")
                for name in batch:
                    lines.append(f"- {name}")
                lines.append("")
        else:
            lines.append("None.")
            lines.append("")

        lines.append(f"### {t['id']} — tldr — batches")
        lines.append("")
        tldr_batches = t["tldr_needed_batches"]
        tldr_total = sum(len(b) for b in tldr_batches)
        if tldr_total:
            lines.append(
                f"Total: {tldr_total} entries across {len(tldr_batches)} batches "
                f"({TLDR_BATCH_SIZE} per batch)."
            )
            lines.append("")
            for i, batch in enumerate(tldr_batches, start=1):
                lines.append(f"#### Batch {i}")
                lines.append("")
                for name in batch:
                    lines.append(f"- {name}")
                lines.append("")
        else:
            lines.append("None.")
            lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def summarize_for_check(report):
    failures = []
    for t in report:
        if t["truncated_desc"]:
            failures.append(f"{t['id']}: {len(t['truncated_desc'])} truncated desc")
        if t["no_tldr"]:
            failures.append(f"{t['id']}: {len(t['no_tldr'])} missing tldr")
        if t["tldr_eq_desc"]:
            failures.append(f"{t['id']}: {len(t['tldr_eq_desc'])} tldr == desc")
        if t["duplicate_names"]:
            failures.append(f"{t['id']}: {len(t['duplicate_names'])} duplicate names")
        if t["missing_required"]:
            failures.append(f"{t['id']}: {len(t['missing_required'])} missing required fields")
        for filter_id, defects in t["filter_defects"].items():
            if defects:
                failures.append(f"{t['id']}: {len(defects)} bad `{filter_id}` values")
    return failures


def main():
    check_mode = "--check" in sys.argv[1:]
    report = build_report()

    if check_mode:
        failures = summarize_for_check(report)
        if failures:
            print("Data quality check FAILED:")
            for line in failures:
                print(f"  - {line}")
            return 1
        print("Data quality check OK: no defects found.")
        return 0

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(render_markdown(report), encoding="utf-8")
    print(f"Wrote {REPORT_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
